### ISSUE TITLE
MaxHeight Problemi

### ISSUE THREAD

**Issue by firatoltulu** [uxrocket/uxrocket.modal#6]
Merhaba,

Modal açıldığında height verilmediği taktirde contentin içeriği fazla olduğunda scroll çıkmıyor, bir maxHeight olmalı diye düşünüyorum, diğer case kullanıcı buttonları göremiyor ve işlem yapamıyor

Height verdiğimizde scroll çıkıyor buda problem teşkil ediyor.

**Comment by bcinarli** [comment]
maxHeight şeklinde bir property tanımı var. Bunu açılan pencerenin yüksekliği için kullanabiliyorsunuz.

https://github.com/uxrocket/uxrocket.modal/blob/master/lib/uxrocket.modal.js#L40 (tanımlandığı yer),
https://github.com/uxrocket/uxrocket.modal/blob/master/lib/uxrocket.modal.js#L236 (eklendiği yer)

**Comment by firatoltulu** [comment]
MaxHeight  verdim, popup açıldı contentde scroll çıktı, buraya kadar normal,
popup x den kapattık, sonra tekrar açtık, scroll kayboldu.

**Comment by bcinarli** [comment]
Modalı link ile mi açıyorsunuz? Yoksa direct-call ile mi? Reponun örnekleri içindeki "Başka bir sayfaya ajax" ile açılan örnekte içerik uzun durumda. `maxHeight: '90%'` olarak tanımlı. Her kapama, açma da problemsiz çalışıyor scroll durumları.

**Comment by firatoltulu** [comment]
direct-call yapıyoruz. px olarak verdik, % deneyelim



2015-11-06 14:37 GMT+03:00 Bilal Çınarlı <notifications@github.com>:

> Modalı link ile mi açıyorsunuz? Yoksa direct-call ile mi? Reponun
> örnekleri içindeki "Başka bir sayfaya ajax" ile açılan örnekte içerik uzun
> durumda. maxHeight: '90%' olarak tanımlı. Her kapama, açma da problemsiz
> çalışıyor scroll durumları.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uxrocket/uxrocket.modal/issues/6#issuecomment-154390001>
> .
>



-- 
Saygılarımla.
İyi Çalışmalar.
------------------------------
Fırat Oltulu
*Solution Architect*

**Comment by bcinarli** [comment]
Şöyle test edebilirsin.

```js
// ajax için
var ajaxSample = $.uxrmodal({ href: 'internal.html', maxHeight: '300px' }),

// ajaxSample.close() - close modal
// ajaxSample.prepare() - reopen modal
```
```js
// html sample
var $html = '<div style="width: 480px; height: 1000px; background-color: #f5f5f5">Hello World</div>',
    htmlSample = $.uxrmodal({ html: $html, maxHeight: '500px' });

// htmlSample.close() - close modal
// htmlSample.prepare() - reopen modal
```

**Comment by firatoltulu** [comment]
Yalnız biz kullanımlarımızda,

bir instance üzerinden çalıştırmıyoruz.
$.uxrmodal({ href:"#Container", maxHeight: '500px' });

hep bu şekilde open yapıyoruz.




On Fri, Nov 6, 2015 at 2:58 PM, Bilal Çınarlı <notifications@github.com>
wrote:

> Şöyle test edebilirsin.
>
> // ajax içinvar ajaxSample = $.uxrmodal({ href: 'internal.html', maxHeight: '300px' }),
> // ajaxSample.close() - close modal// ajaxSample.prepare() - reopen modal
>
> // html samplevar $html = '<div style="width: 480px; height: 1000px; background-color: #f5f5f5">Hello World</div>',
>     htmlSample = $.uxrmodal({ html: $html, maxHeight: '500px' });
> // htmlSample.close() - close modal// htmlSample.prepare() - reopen modal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uxrocket/uxrocket.modal/issues/6#issuecomment-154393053>
> .
>



-- 
Saygılarımla.
İyi Çalışmalar.
------------------------------
Fırat Oltulu
*Solution Architect*

**Comment by bcinarli** [comment]
Yine örnekler içinde aşağıdakini deneyebilirsin.

```js
$.uxrmodal({ href: '#hidden-content', maxHeight: '200px' });
```

**Comment by berkandirim** [comment]
Modal yuklendikten sonra `$.uxrmodal.resize()` calistirilarak modal boyutlari resize edilebilir.

Ornek:
```javascript
$(document).on('uxrload.uxrModal', function() {
    $.uxrmodal.resize();
});
```
